# cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build and deploy appraisers-backend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/appraisers-backend',
      '-f', 'appraisers-backend/Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/appraisers-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      'appraisers-backend',
      '--image', 'gcr.io/$PROJECT_ID/appraisers-backend',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

  # Step 2: Build and deploy appraisers-task-queue
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/appraisers-task-queue',
      '-f', 'appraisers-task-queue/Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/appraisers-task-queue']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      'appraisers-task-queue',
      '--image', 'gcr.io/$PROJECT_ID/appraisers-task-queue',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--no-allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/appraisers-backend'
  - 'gcr.io/$PROJECT_ID/appraisers-task-queue'
