# cloudbuild.yaml

steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend'
    args:
      - build
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/appraisers-backend:$SHORT_SHA'
      - '.'

  # Paso 2: Empujar la imagen Docker al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend'
    args:
      - push
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/appraisers-backend:$SHORT_SHA'

  # Paso 3: Desplegar la imagen a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Backend'
    args:
      - 'run'
      - 'deploy'
      - 'appraisers-backend' # Nombre del servicio en Cloud Run
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/appraisers-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1' # Reemplaza con tu región si es diferente
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Ajusta según tus necesidades de autenticación

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/appraisers-backend:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
