# cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY
# cloudbuild.yaml

steps:
  # Construir y desplegar el servicio principal (main-service)
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'main-service'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/main-service', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/main-service']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'  # Usa una versión actualizada
    entrypoint: gcloud
    args:
      - run
      - deploy
      - main-service  # Nombre único del servicio
      - --image
      - gcr.io/$PROJECT_ID/main-service
      - --region=us-central1
      - --platform
      - managed
      - --allow-unauthenticated

  # Construir y desplegar el procesador de tareas (processor-service)
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'processor-service'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/processor-service', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/processor-service']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'  # Usa una versión actualizada
    entrypoint: gcloud
    args:
      - run
      - deploy
      - processor-service  # Nombre único del servicio
      - --image
      - gcr.io/$PROJECT_ID/processor-service
      - --region=us-central1
      - --platform
      - managed
      - --no-allow-unauthenticated

images:
  - 'gcr.io/$PROJECT_ID/main-service'
  - 'gcr.io/$PROJECT_ID/processor-service'


