# cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Paso 1: Construir y desplegar appraisers-backend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/appraisers-backend',
      '-f', 'appraisers-backend/Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/appraisers-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      'appraisers-backend',
      '--image', 'gcr.io/$PROJECT_ID/appraisers-backend',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

  # Paso 2: Construir y desplegar gestor-colas-appraisers
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/gestor-colas-appraisers',
      '-f', 'gestor-colas-appraisers/Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gestor-colas-appraisers']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      'gestor-colas-appraisers',
      '--image', 'gcr.io/$PROJECT_ID/gestor-colas-appraisers',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--no-allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/appraisers-backend'
  - 'gcr.io/$PROJECT_ID/gestor-colas-appraisers'
