# cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Paso 1: Construir y desplegar main-service
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/main-service',
      '-f', 'main-service/Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/main-service']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      'main-service',
      '--image', 'gcr.io/$PROJECT_ID/main-service',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

  # Paso 2: Construir y desplegar processor-service
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/processor-service',
      '-f', 'processor-service/Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/processor-service']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      'processor-service',
      '--image', 'gcr.io/$PROJECT_ID/processor-service',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--no-allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/main-service'
  - 'gcr.io/$PROJECT_ID/processor-service'

